version: '2'
services:
        db:
                image: postgres
                volumes:
                        - ./tmp/db:/var/lib/postgresql/data
                environment:
                        POSTGRES_USER: 'username'
                        POSTGRES_HOST_AUTH_METHOD: trust
        web:
                build: .
                command: bash -c "rm -f tmp/pids/server.pid && sleep 100000"
                volumes:
                        - .:/petlove
                ports:
                        - "3000:3000"
                depends_on:
                        - db