
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: petlove_development

test:
  <<: *default
  database: petlove_test

production:
  <<: *default
  database: petlove_production
  username: petlove
  password: <%= ENV['PETLOVE_DATABASE_PASSWORD'] %>
